# Generated by Django 4.0 on 2021-12-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=75)),
                ('start_ts', models.DateTimeField(db_index=True)),
                ('end_ts', models.DateTimeField(blank=True, null=True)),
                ('logfile', models.FileField(upload_to='logs/%Y/%m/%d/%H')),
            ],
            options={
                'ordering': ['-start_ts'],
                'index_together': {('start_ts', 'end_ts')},
            },
        ),
    ]
