# Generated by Django 4.0 on 2021-12-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='end_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Timestamp'),
        ),
        migrations.AlterField(
            model_name='log',
            name='start_ts',
            field=models.DateTimeField(db_index=True, verbose_name='Start Timestamp'),
        ),
    ]
