# Generated by Django 4.0 on 2021-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0002_alter_log_end_ts_alter_log_start_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logfile',
            field=models.FileField(blank=True, null=True, upload_to='logs/%Y/%m/%d/%H'),
        ),
    ]
