# Generated by Django 4.0 on 2021-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0003_alter_log_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='process',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
