# Generated by Django 4.0.1 on 2022-01-04 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0004_log_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='logfile',
        ),
        migrations.CreateModel(
            name='LogChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stash.log')),
            ],
            options={
                'ordering': ['-created'],
                'index_together': {('created', 'log')},
            },
        ),
    ]
