# Generated by Django 4.0.1 on 2022-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0006_remove_log_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
